### ISSUE TITLE
Problem with minimal integer encoding check

### ISSUE THREAD

**Issue by robstradling** [kroeckx/x509lint#11]
Certs with serial numbers that begin with 0x00 (to make the integer positive) followed by 0xFF are being incorrectly flagged with the "ASN1 integer not minimally encoded" error.

Example: https://crt.sh/?id=17295920&opt=x509lint

**Comment by kroeckx** [comment]
I already noticed that myself, I was expecting the 0x00 the be in ASN1_INTEGER but it obviously isn't.

**Comment by kroeckx** [comment]
I've disabled that test for now, need to find a good way of replacing it.  I'm just going to close this.
