### ISSUE TITLE
Behaviour when EKU extension omitted

### ISSUE THREAD

**Issue by robstradling** [kroeckx/x509lint#16]
https://crt.sh/?id=32206470&opt=x509lint
"ERROR: Invalid type in SAN entry"

IINM, it's showing that error because x509lint treats certs that omit the EKU extension as invalid for each of the purposes (and the corresponding SubjectAltName fields) that can be enumerated by EKU OIDs.

But isn't no EKU extension essentially equivalent to EKU with the anyExtendedKeyUsage OID?

**Comment by kroeckx** [comment]
On Tue, Sep 20, 2016 at 03:00:20PM -0700, Rob Stradling wrote:
> But isn't no EKU extension essentially equivalent to EKU with the anyExtendedKeyUsage OID?

That at least seems to make sense to me.
