### ISSUE TITLE
Don't LINT certificates that are not SSL/TLS against BRGs

### ISSUE THREAD

**Issue by RufusJWB** [kroeckx/x509lint#29]
I think the behavior of CAB LINT regarding non-TLS certificates is more appropriate: https://crt.sh/?id=1138256051&opt=cablint,x509lint . Maybe you could also disable linting for non-SSL/TLS certificates.

**Comment by kroeckx** [comment]
The certificate you point to has "TLS Web Client Authentication"
in the EKU, so it is not a non-TLS certificate.

The BRs only apply to server authentication, but most of the
things in it really should apply to any kind of certificate.

I can agree that "Invalid type in SAN entry" should probably not
be returned. I'm currently not sure about "Subject with givenName
or surname but without the CAB IV policy oid". But I think the
other 2 errors are valid.

**Comment by RufusJWB** [comment]
Understood. Let's see what the WG for SMIME will come up with.

**Comment by kroeckx** [comment]
The 2 others have been removed, the other 2 stayed
