### ISSUE TITLE
id-kp-clientAuth certificates incorrectly trigger ERR_POLICY_BR 

### ISSUE THREAD

**Issue by jdkasten** [kroeckx/x509lint#35]
Certificates that only contain a clientAuth key purpose ID are allowed for subscriber certificates according to the BRs.

```
extKeyUsage (required)
Either the value id-kp-serverAuth [RFC5280] or id-kp-clientAuth [RFC5280] or
both values MUST be present. id-kp-emailProtection [RFC5280] MAY be present.
Other values SHOULD NOT be present. The value anyExtendedKeyUsage MUST NOT be
present.
```
7.1.2.3 Subscriber Certificates - Page 70. 
https://cabforum.org/wp-content/uploads/CA-Browser-Forum-BR-1.7.3.pdf

However, certificates that only contain a clientAuth EKU with a BR OID return a
"ERROR: Baseline Requirements policy present for non server authentication certificate" message.

It appears that the logic within checks.c : CheckPolicy is not precise.
```
if (GetBit(cert_info, CERT_INFO_SERV_AUTH) || GetBit(cert_info, CERT_INFO_ANY_EKU) || GetBit(cert_info, CERT_INFO_NO_EKU))
	{
		if ((IsNameObjPresent(subject, obj_givenName) || IsNameObjPresent(subject, obj_surname))
			&& !CabIVPresent)
		{
			/* Required by CAB 7.1.4.2.2c */
			SetError(ERR_NAME_NO_IV_POLICY);
		}
	}
	else
	{
		if (DomainValidated || IndividualValidated || CabIVPresent)
		{
			SetError(ERR_POLICY_BR);
		}
	}
```
Original commit: https://github.com/kroeckx/x509lint/commit/4b596b109a0533c4631b081c7081597a0e72bdaf

**Comment by kroeckx** [comment]
It actually has the text in it since version 1. The BRs also say `These Requirements only address Certificates intended to be used for authenticating servers accessible through the Internet`. So I think the BR is self-conflicting.

**Comment by jdkasten** [comment]
Thank you for the reply. I understand the confusion and wish the BRs were more clear in this regard. Perhaps a ballot can clean up the intent.

IIUC with that interpretation of the BRs, only serverAuth should be allowed?

The vast majority of BR compliant certificates on the Internet contain both serverAuth and clientAuth. It seems like issuing a more restrictive certificate that only contains clientAuth is strictly better than issuing permissive certificates with both key purpose IDs. All other validation/requirements remaining equal.

**Comment by kroeckx** [comment]
I expect that some certificates can be used for both client and server authentication, and that it would then have both. You can have both servers authenticate each other, and depending on who initiates the connection you're a client or server. An example for that is SMTP where it can act as both client and server. But for SMTP there are practical reasons not to do that in the general case. I'm currently not convinced that client authentication without server authentication falls under the BRs.

**Comment by jdkasten** [comment]
I understand client+server usecases, I was more or less trying to point out that most publicly trusted WebPKI certificates could be used strictly for clientAuth today. Almost every validation/issuance performed under the requirements of the BRs grants both permissions by default.

I don't believe the BR policy OID can be safely dropped from pure clientAuth certificates given the requirements on the issuing CAs. (e.g. https://docs.microsoft.com/en-us/security/trusted-root/program-requirements A.10; and 7.1.6.4 of BRs)

I think this leaves us with an unsatisfying result.

Clearly, the certificate profile of subscriber certificates (7.1.2.3) conflicts with the sentence you linked in the introduction and that should be rectified. Until then, it seems like the "safest" way forward is to grant the unnecessary serverAuth permission to these certificates and avoid the case entirely. 

I appreciate the discussion. I will close this for now and seek to add clarification to the BRs.
